# Workflow : 전체 흐름
name : Github Actions 실행시켜보기

on:
  push:
    branches:
      - main
# Workflow 내부 : 여러개의 Job으로 구성
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    # 하나의 Job 내부 : 여러개의 Step으로 구성
    steps:  
      - name: Hello World 출력하기
        run: echo "Hello World"
      - name : 여러 명령어 문장 작성하기
        run: |
          echo "Good Morning"
          echo "Everyone"
          pwd